# Generated by Django 4.2.1 on 2024-06-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='infante',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='infantes',
            field=models.ManyToManyField(blank=True, related_name='propiedades', to='mainapp.infante'),
        ),
    ]
