# Generated by Django 4.2.1 on 2024-06-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_propiedad_infante_propiedad_infantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='infante',
            name='alergias',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='infante',
            name='antecendetes_medicos',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='infante',
            name='prevision',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='infante',
            name='rut',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
