# Generated by Django 4.2.1 on 2024-06-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_propiedad_infantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='infantes',
            field=models.ManyToManyField(blank=True, related_name='propiedades', to='mainapp.infante'),
        ),
    ]
