# Generated by Django 4.2.1 on 2024-06-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_propiedad_infantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios_emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bomberos', models.CharField(max_length=50)),
                ('numero_carabineros', models.CharField(max_length=50)),
                ('numero_asistencia_medica', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Institucion',
        ),
    ]
