# Generated by Django 4.2.1 on 2024-06-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_servicios_emergencia_delete_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='servicios_emergencia',
            field=models.ManyToManyField(blank=True, related_name='servicios_propiedad', to='mainapp.servicios_emergencia'),
        ),
    ]
